### PR TITLE
Fix iOS 11 issue with adding subviews to UIVisualEffectView

### LINKED ISSUE #46: Do not add subviews directly to the visual effect view itself.
Pod crashes app on ios 11 

I think line 67 in InfoView.swift is at fault here !?

Example code: 

                self.barcodeScanner = BarcodeScannerController()
                self.barcodeScanner?.codeDelegate = self
                self.barcodeScanner?.errorDelegate = self
                //self.barcodeScanner?.view.subviews[0].isHidden = true
                
                return barcodeScanner

Console error:

*** Assertion failure in -[BarcodeScanner.InfoView _addSubview:positioned:relativeTo:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3683.300.2/UIVisualEffectView.m:1364

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<UILabel: 0x127d23f60; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <_UILabelLayer: 0x1c40992d0>> has been added as a subview to <BarcodeScanner.InfoView: 0x127d51a10; baseClass = UIVisualEffectView; frame = (0 0; 0 0); layer = <CALayer: 0x1c4227d40>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'

*** First throw call stack:
(0x184f9d858 0x183774528 0x184f9d72c 0x185ad2280 0x18be0d26c 0x10344d2c8 0x10343fb4c 0x10344d3f8 0x10398bf7c 0x1037bc73c 0x10344d0b4 0x10344d424 0x10344cd14 0x10343b1d0 0x10343f204 0x10343fe44 0x18b7ab6bc 0x18b7ab294 0x18b92fafc 0x18b8529d0 0x18b8525f0 0x18b8524f8 0x18b7a8a64 0x1887816e4 0x18878579c 0x1886f83f8 0x18871de44 0x18871ec68 0x184f43a6c 0x184f41514 0x184f419f8 0x184e60280 0x186971f94 0x18b80f0f0 0x102cd8cc0 0x183c51e40)

libc++abi.dylib: terminating with uncaught exception of type NSException

### PR DESCRIPTION
**Pull request by nickskull**
Fixes #46.

### CODE REVIEW

**Comment by vadymmarkov** [comment]
Thanks!

File: Sources/InfoView.swift [hunk 1]
```diff
@@ -64,7 +64,11 @@ class InfoView: UIVisualEffectView {
     super.init(effect: blurEffect)
 
     [label, imageView, borderView].forEach {
-      addSubview($0)
```
Comment (AhmAbdallah) [inline Sources/InfoView.swift]: When I used this solution I have a crash because you adding this before if condition 
2018-05-07 11:39:40.849131+0300 Joker[7443:4905523] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<UILabel: 0x105b2c8f0; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <_UILabelLayer: 0x1c428b810>> has been added as a subview to <BarcodeScanner.InfoView: 0x105a3d9e0; baseClass = UIVisualEffectView; frame = (0 0; 0 0); layer = <CALayer: 0x1c02238c0>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'

Solution:- just comment this line and this solution will work as a charm.

Comment (AhmAbdallah) [reply Sources/InfoView.swift]: The solution:- 
init() {
    let blurEffect = UIBlurEffect(style: .extraLight)
    super.init(effect: blurEffect)
    
    [label, imageView, borderView].forEach {
             // addSubview($0)
                if #available(iOS 11.0, *) {
                       contentView.addSubview($0)
                   } else {
                       addSubview($0)
                    }
    }
    
    status = Status(state: .scanning)
  }
